
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 25 00:30:07 CST 2018
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_MULTIPLY = 29;
  public static final int RW_TO = 17;
  public static final int RW_BEGIN = 3;
  public static final int RW_PROGRAM = 14;
  public static final int RW_UNTIL = 19;
  public static final int OP_LESSLESS = 25;
  public static final int OP_TWOPOINTSEGUAL = 26;
  public static final int OP_RIGHTPARENTHESIS = 33;
  public static final int ENTERO = 52;
  public static final int STRING_BLOCK = 56;
  public static final int DATA_TYPE = 2;
  public static final int OP_DIVIDE = 30;
  public static final int OPB_GREATEREQUAL = 43;
  public static final int RW_DO = 5;
  public static final int NUMERAL_CHARACTER = 57;
  public static final int OP_DIV = 38;
  public static final int OP_TWOPOINTS = 41;
  public static final int OPB_OR = 48;
  public static final int OPB_LESSEQUAL = 45;
  public static final int RW_END = 7;
  public static final int RW_FUNCTION = 10;
  public static final int RW_WHILE = 21;
  public static final int OP_MOD = 31;
  public static final int RW_VAR = 20;
  public static final int SCIENTIFIC_NOTATION = 54;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int OP_LESSEQUAL = 35;
  public static final int RW_FALSE = 8;
  public static final int OP_PLUSPLUS = 24;
  public static final int OPB_EQUAL = 42;
  public static final int RW_TRUE = 18;
  public static final int REAL = 53;
  public static final int OP_SEMI = 40;
  public static final int OPB_LESS = 46;
  public static final int OPB_NOT = 50;
  public static final int OPB_AND = 49;
  public static final int RW_IF = 11;
  public static final int OP_MULTEQUAL = 36;
  public static final int OP_LEFTPARENTHESIS = 32;
  public static final int OP_LESS = 28;
  public static final int STRING_LINE = 55;
  public static final int RW_CONST = 4;
  public static final int RW_OF = 12;
  public static final int OPB_DIFERENT = 47;
  public static final int RW_FOR = 9;
  public static final int OP_COMMA = 39;
  public static final int OP_PLUSEQUAL = 34;
  public static final int RW_WHITE = 22;
  public static final int RW_ELSE = 6;
  public static final int OPB_GREATER = 44;
  public static final int RW_READ = 15;
  public static final int RW_PROCEDURE = 13;
  public static final int OP_PLUS = 27;
  public static final int RW_WRITE = 23;
  public static final int RW_THEN = 16;
  public static final int IDENTIFIER = 51;
  public static final int OP_DIVEQUAL = 37;
}

